version: '3.3'

services:

  mariadb:
#    image: 'bitnami/mariadb:latest'
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#      - 'mariadb_data:/bitnami'
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3308:3306'
    volumes:
      - mariadb_data:/var/lib/mysql


  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '10580:3000'
    volumes:
      - 'redmine_data:/bitnami'
    depends_on:
      - mariadb
    environment:
#      - REDMINE_USERNAME: Redmine application username. Default: user
#      - REDMINE_PASSWORD: Redmine application password. Default: bitnami1
#      - REDMINE_EMAIL: Redmine application email. Default: user@example.com
#      - REDMINE_LANG: Redmine application default language. Default: en
#      - REDMINE_DB_USERNAME: Root user for the application database. Default: root
#      - REDMINE_DB_PASSWORD: Root password for the database.
      - REDMINE_DB_PASSWORD=admin
#      - REDMINE_DB_MYSQL: Hostname for MySQL server. Default: mariadb
#      - REDMINE_DB_POSTGRES: Hostname for PostgreSQL server. No defaults
#      - REDMINE_DB_PORT_NUMBER: Port used by database server. Default: 3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 10581:8080
    links:
      - mariadb:db
    command: php -S 0.0.0.0:8080 -t /var/www/html

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local


