---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: adminer
  strategy: {}
  template:
    metadata:
      labels:
        app.service: adminer
    spec:
      containers:
        - args:
            - php
            - -S
            - 0.0.0.0:8080
            - -t
            - /var/www/html
          image: adminer
          name: adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: adminer
  name: adminer
spec:
  type: NodePort
  ports:
    - name: "10081"
      port: 10081
      targetPort: 8080
      nodePort: 30081
  selector:
    app.service: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: mydb
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: mydb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.service: mydb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: redmine
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          image: mysql:5.7
          name: mydb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mydb-data
      restartPolicy: Always
      volumes:
        - name: mydb-data
          hostPath:
            path: /mnt/mydb-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: mydb
  name: mydb
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app.service: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: redmine
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.service: redmine
    spec:
      containers:
        - env:
            - name: REDMINE_DB_MYSQL
              value: mydb
            - name: REDMINE_DB_PASSWORD
              value: admin
          image: redmine
          name: redmine
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/redmine/files
              name: redmine-data
      restartPolicy: Always
      volumes:
        - name: redmine-data
          hostPath:
            path: /mnt/redmine-data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: redmine
  name: redmine
spec:
  type: NodePort
  ports:
    - name: "13000"
      port: 13000
      targetPort: 3000
      nodePort: 30300
  selector:
    app.service: redmine
