---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol01
  labels:
    type: local
spec:
  storageClassName: redmine
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redmine-vol01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol02
  labels:
    type: local
spec:
  storageClassName: redmine
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redmine-vol02"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
    spec:
      containers:
        - args:
            - php
            - -S
            - 0.0.0.0:8080
            - -t
            - /var/www/html
          image: adminer
          name: adminer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  type: NodePort
  ports:
    - name: "10081"
      port: 10081
      targetPort: 8080
      nodePort: 30081
  selector:
    io.kompose.service: adminer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mydb-data
  name: mydb-data
spec:
  storageClassName: redmine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mydb
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mydb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mydb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: redmine
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          image: mysql:5.7
          name: mydb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mydb-data
      restartPolicy: Always
      volumes:
        - name: mydb-data
          persistentVolumeClaim:
            claimName: mydb-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mydb
  name: mydb
spec:
  type: NodePort
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    io.kompose.service: mydb
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redmine-data
  name: redmine-data
spec:
  storageClassName: redmine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: redmine
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redmine
    spec:
      containers:
        - env:
            - name: REDMINE_DB_MYSQL
              value: mydb
            - name: REDMINE_DB_PASSWORD
              value: admin
          image: redmine
          name: redmine
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/redmine/files
              name: redmine-data
      restartPolicy: Always
      volumes:
        - name: redmine-data
          persistentVolumeClaim:
            claimName: redmine-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: redmine
  name: redmine
spec:
  type: NodePort
  ports:
    - name: "13000"
      port: 13000
      targetPort: 3000
      nodePort: 30300
  selector:
    io.kompose.service: redmine
status:
  loadBalancer: {}
